sudo: false
language: node_js
node_js:
- '0.12'
script:
- npm test && npm run build
notifications:
  email:
  - jari@holderdeord.no
  hipchat:
    rooms:
      secure: L0RdNUzi3ewPNo9Di2wOrq4ZHl4XysUeoG6jTEaHU1rMaAshR1U1POTKAocfPwFtfjtuC9rJJT0MRcFXeWuCsVHcJ1lokKq7Pas+5UfgVrwXT2fl6bPU1uDUzTU1ps5ZZqBcdr3+uVFYhyNEM4NhveHn9fBZlZCrPdBuFc5QXlIwZII0nMUYVMmpqbbYjORzHwjUAbI3N2RckALaru4CEhqlpPShE6QbDZhLiWDhCANqZdMYrdLJoam8f11R5IMoACapl7mqS+NCSW3UCKt0gdPAxnXg+lKUCOHwNVBIWR7VqsD8VZWCaTbGeTb3NJQGnRQ3oXtc53kEOUmqP6WJZOmUHSZL9JCJyGppY2jjV2x5eLYFU6mZBIWTsgu2vSjTpKaE5doOcQhN5czIuY9Ny2MUJHfc6qb3wf+wd1S5/ScS2X/tWlrdKKA5V9BLIKRyksMEwvzeEsYr+1cmnW+rJxGyC41F3R6tPIVC0R4g3ZsWyaLsf/QawMai42c53sAnifoEQHl9ZUhXUdPgKd/W6RN6Nn9IUYBWdWD45chNFyWg+s7XhKQnyJcBW0z1Wodc7dWADTSzR1UHL8VP906cGMMIM+h4lh8CdM1tqPOaq4tyZRjqYS2Fk+rW/EDu8BNn/8k8huZDtNQ4+rxxbyTe9BKPLnlNrFNPYVMyrIiMbI0=
  slack:
    secure: EOO6zTuaxWSPB1+NUkwz6qpPn33rffXrBaIzLTSbgDFx+fyNKDeiv1KHOXOf3ul+Wc3TD+TlV6PZSuukRcGtbz56tfjacFPWdEuFDvB7QKAeD27JD7qcr/5LWxEIIbvHP+Hzj8EXnomprxB10xssNrl0a5zI3r55dkEdvkjSPWG6BEKBNM3uILBaGV1ICgu9gMZRJ3dc5GcvtqfYSwd9ZteUuYnA5LwgkIyRItjD5ZQD65dsa6Ugkm2xqlzTehMc1hHDGvmHHFxoBMHcZpB9G+DzRksmpnMI2e5r5qam20FYT4aYa2RoIf1QF9YtoKc84GwYIL6bCfM47NnmOfRDL8eFSQtnplUVg9Hd51pTZgfD6+A1pPRGV0p7lCPzhBExoVjkLX2PBUxsP4kQguQ32rq2GAGUnDpXRGBPK+jMookVsyrR1F3tXUB5bQNmKCOYiEGLKhBxV0PFKu2wghLRmFGZic2tFF9mpf4MjE/9rqlovKfYshOitDCk0cTlb55xv/Mr8W6ZlmqK9kV7nokiEvyiwhaLLFNCcBut++1EXdJVx8Mfj9K21la02zjlRBPTTrHhhOyeTSi8eYOAAmp4z30V6YSgvwvGBNRwfauK9cx+ohLuGUbScY67x46iTpHHceuNlZL/qNZyHuFISqzg6q8n3ZeDZ1/CQBlTGGF6qFU=
